import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ReportDataPayload } from "./reportDataService";
import { chartToImageService } from "./chartToImageService";

function formatRp(amount: number) {
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(amount);
}

export const pdfExecutiveGenerator = {
  async generateExecutiveReport(data: ReportDataPayload, onProgress?: (step: string, progress: number) => void) {
    onProgress?.("Initialize PDF Engine...", 10);
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;
    
    const orange = [249, 115, 22] as [number, number, number];
    const dark = [17, 17, 17] as [number, number, number];

    const addHeaderFooter = (pageNum: number) => {
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text("CONFIDENTIAL - SERU.NI COFFEE ENTERPRISE", 14, 10);
      doc.text(`Generated: ${data.generatedAt} by ${data.generatedBy}`, 14, pageHeight - 10);
      doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 10);
    };

    // PAGE 1: COVER
    onProgress?.("Building Executive Cover...", 20);
    doc.setFillColor(...orange);
    doc.rect(0, 0, pageWidth, 40, 'F');
    doc.setTextColor(255);
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text("SERU.NI COFFEE", 14, 25);
    
    doc.setTextColor(...dark);
    doc.setFontSize(36);
    doc.text("Executive Financial Report", 14, 80);
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`Reporting Period: ${data.period.toUpperCase()}`, 14, 95);
    doc.text(`Generated At: ${data.generatedAt}`, 14, 105);
    doc.text(`Generated By: ${data.generatedBy}`, 14, 115);
    
    doc.setDrawColor(...orange);
    doc.setLineWidth(2);
    doc.line(14, 130, 80, 130);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text("This document contains highly confidential financial data.", 14, 145);
    doc.text("Do not distribute outside of executive management.", 14, 152);

    addHeaderFooter(1);

    // PAGE 2: EXECUTIVE SUMMARY
    doc.addPage();
    onProgress?.("Aggregating KPIs...", 35);
    doc.setFontSize(22);
    doc.setTextColor(...dark);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary", 14, 20);
    
    const drawKpi = (title: string, value: string, x: number, y: number) => {
      doc.setDrawColor(230, 230, 230);
      doc.setFillColor(250, 250, 250);
      doc.rect(x, y, 85, 30, 'FD');
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(title, x + 5, y + 10);
      doc.setFontSize(16);
      doc.setTextColor(...dark);
      doc.setFont("helvetica", "bold");
      doc.text(value, x + 5, y + 22);
    };

    drawKpi("Total Revenue", formatRp(data.summary.totalRevenue), 14, 30);
    drawKpi("Gross Cash", formatRp(data.summary.grossCash), 105, 30);
    drawKpi("Gross QRIS", formatRp(data.summary.grossQris), 14, 65);
    drawKpi("Net Cash", formatRp(data.summary.netCash), 105, 65);
    drawKpi("Total Orders", data.summary.totalOrders.toString(), 14, 100);
    drawKpi("Total Cups Sold", data.summary.totalCups.toString(), 105, 100);
    drawKpi("Avg Order Value", formatRp(data.summary.averageOrderValue), 14, 135);
    drawKpi("Avg Cups / Trx", data.summary.averageCupsPerTrx.toFixed(2), 105, 135);

    addHeaderFooter(2);

    // PAGE 3: INSIGHTS
    doc.addPage();
    onProgress?.("Generating AI Insights...", 50);
    doc.setFontSize(22);
    doc.text("Business Insights", 14, 20);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    
    const insights = [
      `Revenue Analysis: Total revenue stands at ${formatRp(data.summary.totalRevenue)}.`,
      `Payment Distribution: QRIS contributes ${data.insights.qrisPercentage.toFixed(1)}%, while Cash contributes ${data.insights.cashPercentage.toFixed(1)}%.`,
      `Best Performing Outlet: ${data.insights.bestOutlet}`,
      `Lowest Performing Outlet: ${data.insights.lowestOutlet}`,
      `Top Selling Product: ${data.insights.bestProduct}`,
      `Highest Performing Crew: ${data.insights.bestCrew}`,
      `Average Transaction Value: ${formatRp(data.insights.averageTrx)}`,
      `Peak Sales Day: ${data.insights.peakSalesDay}`,
      `Most Active Hour: ${data.insights.mostActiveHour}`,
      `Preferred Payment Method: ${data.insights.topPaymentMethod}`
    ];

    let yPos = 40;
    insights.forEach(insight => {
      doc.circle(16, yPos - 1.5, 1.5, 'F');
      doc.text(insight, 22, yPos);
      yPos += 12;
    });

    addHeaderFooter(3);

    // PAGE 4, 5, 7, 8: TABLES
    doc.addPage();
    onProgress?.("Building Financial Tables...", 65);
    doc.setFontSize(22);
    doc.text("Outlet Performance", 14, 20);
    
    autoTable(doc, {
      startY: 30,
      head: [['Outlet', 'Orders', 'Cups', 'Gross Rev', 'Cash', 'QRIS']],
      body: data.outlets.map(o => [o.name, o.orders, o.cups, formatRp(o.gross), formatRp(o.cash), formatRp(o.qris)]),
      theme: 'grid',
      headStyles: { fillColor: orange }
    });
    
    doc.setFontSize(22);
    doc.text("Crew Performance", 14, (doc as any).lastAutoTable.finalY + 20);
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 30,
      head: [['Crew', 'Outlet', 'Orders', 'Cups', 'Gross Rev']],
      body: data.crews.map(c => [c.name, c.outlet, c.orders, c.cups, formatRp(c.gross)]),
      theme: 'grid',
      headStyles: { fillColor: orange }
    });

    addHeaderFooter(4);

    // PAGE 11: LEDGER (Landscape if needed, but we keep it simple for now)
    doc.addPage();
    onProgress?.("Generating Ledger & Settlement...", 80);
    doc.setFontSize(22);
    doc.text("Transaction Ledger", 14, 20);
    
    // Limit ledger to 100 for PDF to avoid memory crash
    const ledgerLimit = data.ledger.slice(0, 100);
    autoTable(doc, {
      startY: 30,
      head: [['Invoice', 'Time', 'Type', 'Outlet', 'Payment', 'Total']],
      body: ledgerLimit.map(l => [l.invoice || '-', l.time, l.type, l.outlet, l.payment, formatRp(l.total)]),
      theme: 'grid',
      headStyles: { fillColor: orange },
      styles: { fontSize: 8 }
    });
    addHeaderFooter(5);

    // CHARTS PAGE
    doc.addPage();
    onProgress?.("Rendering Offline Charts...", 90);
    doc.setFontSize(22);
    doc.text("Performance Charts", 14, 20);
    
    try {
      const chartBase64 = await chartToImageService.generateChart({
        type: 'doughnut',
        data: {
          labels: ['QRIS', 'Cash'],
          datasets: [{ data: [data.summary.grossQris, data.summary.grossCash], backgroundColor: ['#F97316', '#111111'] }]
        }
      });
      if (chartBase64) {
        doc.setFontSize(14);
        doc.text("Payment Distribution", 14, 40);
        doc.addImage(chartBase64, 'PNG', 14, 45, 80, 80);
      }
    } catch (e) {
      console.error(e);
    }

    addHeaderFooter(6);

    // SIGNATURE PAGE
    doc.addPage();
    onProgress?.("Finalizing Signatures...", 95);
    doc.setFontSize(22);
    doc.text("Validation & Signatures", 14, 20);
    
    doc.setFontSize(12);
    doc.text("Prepared By:", 14, 60);
    doc.text("_________________________", 14, 90);
    doc.text("System / Manager", 14, 98);

    doc.text("Approved By:", 110, 60);
    doc.text("_________________________", 110, 90);
    doc.text("Executive Owner", 110, 98);

    addHeaderFooter(7);

    let fileName = `Executive_Report_${data.period}.pdf`;
    if (data.period === 'today') fileName = `Executive_Report_${new Date().toISOString().split('T')[0]}.pdf`;
    
    onProgress?.("Downloading Report...", 100);
    doc.save(fileName);
  }
};
