import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateFinancialAuditPDF(payload: any, periodLabel: string) {
  const doc = new jsPDF("p", "pt", "a4");

  const orange: [number, number, number] = [234, 88, 12];
  const black: [number, number, number] = [20, 20, 20];
  const lightGray: [number, number, number] = [240, 240, 240];

  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 1. Header
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(black[0], black[1], black[2]);
  doc.text("SERUNI", 40, 50);

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("ENTERPRISE POINT OF SALE", 40, 65);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(orange[0], orange[1], orange[2]);
  doc.text("Laporan Audit Finansial Enterprise", 40, 85);

  doc.setDrawColor(orange[0], orange[1], orange[2]);
  doc.setLineWidth(2);
  doc.line(40, 95, pageWidth - 40, 95);

  // 2. Info Period
  doc.setFontSize(10);
  doc.setTextColor(black[0], black[1], black[2]);
  const dateStr = new Date().toLocaleString("id-ID");
  doc.text(`Periode Laporan: ${periodLabel}`, 40, 115);
  doc.text(`Tanggal Cetak: ${dateStr}`, 40, 130);

  let startY = 150;

  // 3. KPI Summary
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("RINGKASAN KPI", 40, startY);
  startY += 15;

  const { kpi, shiftMaster, exceptions } = payload || {};
  
  const formatRupiah = (val: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(val || 0);

  const kpiData = [
    ["Gross Revenue", formatRupiah(kpi?.gross_revenue)],
    ["Net Revenue", formatRupiah(kpi?.net_revenue)],
    ["Total Expense", formatRupiah(kpi?.operational_expense)],
    ["Total Cup Terjual", `${kpi?.total_cups || 0} Cup`],
    ["Total Transaksi", `${kpi?.total_transactions || 0}`],
  ];

  autoTable(doc, {
    startY: startY,
    head: [["Indikator", "Nilai"]],
    body: kpiData,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: orange, textColor: 255, fontStyle: "bold" },
  });

  startY = (doc as any).lastAutoTable.finalY + 30;

  // 4. Exception Report (if any)
  if (exceptions && exceptions.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(220, 38, 38); // Red
    doc.text("SMART EXCEPTION REPORT", 40, startY);
    startY += 15;

    const exceptionData = exceptions.map((ex: any) => [
      ex.crew_name || "Unknown",
      ex.exception_type,
      formatRupiah(ex.amount),
      new Date(ex.end_time).toLocaleString("id-ID")
    ]);

    autoTable(doc, {
      startY: startY,
      head: [["Crew", "Tipe Anomali", "Nominal", "Waktu Tutup"]],
      body: exceptionData,
      theme: "grid",
      styles: { font: "helvetica", fontSize: 9, cellPadding: 5 },
      headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: "bold" },
    });
    
    startY = (doc as any).lastAutoTable.finalY + 30;
  }

  // 5. Shift History
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(black[0], black[1], black[2]);
  doc.text("SHIFT AUDIT HISTORY", 40, startY);
  startY += 15;

  const shiftData = (shiftMaster || []).map((s: any) => {
    const isKasirPusat = !s.crew_name || s.crew_name.toLowerCase() === 'system' || s.crew_name.toLowerCase().includes('kasir pusat');
    
    let selisihKasText = "-";
    if (isKasirPusat && s.shift_status === 'CLOSED') {
      selisihKasText = formatRupiah(Number(s.cash_difference || 0));
    } else if (!isKasirPusat) {
      selisihKasText = "Settlement Crew";
    } else if (s.shift_status === 'OPEN') {
      selisihKasText = "Sedang Berjalan";
    }

    return [
      s.crew_name || "System",
      s.outlet_id || s.location || "Grobak",
      s.shift_status,
      `${s.total_cups || 0} Cup`,
      formatRupiah(s.gross_revenue),
      formatRupiah(s.operational_expense),
      selisihKasText,
      isKasirPusat && s.shift_status === 'CLOSED' ? `${s.audit_score}/100` : "-"
    ];
  });

  autoTable(doc, {
    startY: startY,
    head: [["Crew", "Lokasi", "Status", "Cup", "Sales", "Expense", "Selisih Kas", "Score"]],
    body: shiftData,
    theme: "grid",
    styles: { font: "helvetica", fontSize: 8, cellPadding: 5 },
    headStyles: { fillColor: lightGray, textColor: black, fontStyle: "bold" },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Halaman ${i} dari ${pageCount} | Generated by Seruni Enterprise POS`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: "center" }
    );
  }

  doc.save(`Laporan_Audit_Finansial_${periodLabel}.pdf`);
}
